### PR TITLE
Publish Docs to The NPM Registry

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Comment by khajavi** [comment]
This work is ready for review.

**Review by adamgfraser — APPROVED** [review]

**Comment by pshirshov** [comment]
Tbh I don't like the removal of our description from readme.md. It doesn't constitute a full website/documentation page and it really make sense to keep it where it was.

**Comment by pshirshov** [comment]
Please keep the readme as it is.

The docs site may contain a copy of it for the starters, though it definitely should contain different information, like usage examples, some details on the internals and library design, etc.

**Comment by adamgfraser** [comment]
@pshirshov Sorry about that!

@khajavi You want to revert?

**Comment by pshirshov** [comment]
I already fixed the readme, the rest is fine but the docs should be very different from the readme. Maybe I'll write something one day, that may make it easier for potential contributors to understand what's happening under the hood.

**Comment by adamgfraser** [comment]
@pshirshov Thanks for doing that!

**Pull request merged**
