### PR TITLE
update to scala 3.0.0-M3

### PR DESCRIPTION
**Pull request by scalavision**
update to scala 3.0.0-M3, I have not tested it extensively.

### CODE REVIEW

**Comment by scalavision** [comment]
@neko-kai , could this be merged, or do you want to wait for the RC1 candidate?

**Comment by neko-kai** [comment]
@scalavision
Sorry, I missed the notification about your PR, no intention about it!

**Comment by neko-kai** [comment]
Thanks for following up

**Comment by neko-kai** [comment]
@scalavision 
Hi, I've added commit access for you, you may make a release on your own on next dotty update if necessary. (use `sbt release` to push new versions)

**Comment by scalavision** [comment]
thank you very much @neko-kai ! :-) no worries, I didn't want to disturb too much during Christmas holidays. Happy new year :-)

**Pull request merged**
