### PR TITLE
Add ci workflow to publish docs

### LINKED ISSUE #458: Publish Project Docs On Release Events
The [last published documentation](https://www.npmjs.com/package/@zio.dev/izumi-reflect/v/2.2.3?activeTab=versions) of this project corresponds to `2.2.3`.

We need to update the CI to publish docs when a release event occurs. Please refer to [this link](https://zio.dev/contributing-to-zio-ecosystem#publishing-documentation) for more information.

This fixes the issue reported [here](https://github.com/zio/zio/issues/7678).

### PR DESCRIPTION
**Pull request by varshith257**
/claim #458
Closes #458

### CODE REVIEW

**Comment by varshith257** [comment]
@neko-kai Could you have a look at secrets needed?

**Comment by pshirshov** [comment]
Well, all the secrets are managed at the org level :)

Also, may I ask you to not change the formatting please? This style differs from the default Idea formatter, so it would be annoying and it doesn't really bring any value.

**Comment by varshith257** [comment]
@pshirshov I think they got changed with my Default yml formatter on my IDE 😄.

I will revert those format issues

**Comment by pshirshov** [comment]
Once you rebase, the build should be green. 

Though there is a bit more in this. This comment remains valid: https://github.com/zio/izumi-reflect/pull/339#issuecomment-1316070475

We need to do more than just publishing our readme, we should create a documentation stub ( which will be used for https://github.com/zio/izumi-reflect/issues/340 ). There is something created by the previous contributor in the ./docs folder but it's unmaintained.

We need to find a way to both have a nice readme and include a part of it into our documentation. I believe, there are no inclusions in Github markdown, so we need something like that:

1. Our current readme remains as it is
2. We have a documentation stub in `./docs` folder.
3. The doc publishing job takes our readme, strips irrelevant parts (we need to figure out how to mark them) and inserts into the docs which are about to be published. Currently I would like to exclude the "build" and the github badges.

**Comment by pshirshov** [comment]
Regarding marking the relevant and irrelevant parts, github markdown supports comments, so probably we should just have lines like `<!--- docs:start ---> ` and ```<!--- docs:end--->```, plus some sed/awk magic.

**Review by pshirshov — CHANGES_REQUESTED** [review]
See my comments

**Comment by varshith257** [comment]
@pshirshov Does it mean to eradicate ./docs folder?

**Comment by pshirshov** [comment]
Another collaborator already opened a P/R which looks correct: https://github.com/zio/izumi-reflect/pull/491

I don't know how to handle this situation, so probably I'll merge the one which is completed first.

**Comment by varshith257** [comment]
@pshirshov If the PR isn't got reviewed and if another contributor opened a PR alongside me for the same issue that's ok and reviewer goes with which matches close to the solution.

#491 is entirely built upon my PR reviews 🤦

**Comment by varshith257** [comment]
@pshirshov If the PR isn't got reviewed and if another contributor opened a PR alongside me for the same issue that's ok and reviewer goes with which matches close to the solution.

#491 is entirely built upon my PR reviews and this PR isn't stale 🤦

I don't what @Dhanus3133 thought to open an another PR with it 🤔

**Comment by Dhanus3133** [comment]
@varshith257 I noticed that the issue was still open, so I wanted to raise a PR that could close the issue itself. Yes, I saw the comments on your PR by the maintainer and implemented them the way they need accordingly. I want to clarify that I didn't copy any of your code; I developed my solution independently using references from other Zio's repositories. My intention wasn't to undermine your work but to solve the issue.

Since I didn't copy or use any of your code as a reference, I'm happy to let the maintainer decide how to proceed, and I'm fine with whatever they choose.

**Comment by varshith257** [comment]
@Dhanus3133 I am not pretended you copied my code . My PR is already in the way of solving, and got reviews and you again made a duplicate efforts with solving review comments

Anyway the better thing here is let's collaborate on this issue .

**Comment by Dhanus3133** [comment]
> Anyway the better thing here is let's collaborate on this issue .

Since the issue is almost resolved, collaboration isn’t needed here, but I’m open to teaming up on future issues!

**Comment by varshith257** [comment]
@pshirshov Since the other contributor worked upon this PR review comments(as the PR hasn't gone inactive though), I wished to collaborate rather than make duplicate efforts on both ends(AFAICT the other contributor isn't open to collaborating)

> I don't know how to handle this situation

I have been working and contributing to ZIO for the past 5 months and I have also seen a similar kind of situation, you can see collaborations here(where I have worked on reviewer comments and collaborated with other contributor who also worked on it)
https://github.com/zio/zio/pull/8973

[PS: I am not going for tik for tack, just to say everyone's efforts are valued, so I welcomed other contributor for collaborating  ]

**Comment by Dhanus3133** [comment]
@varshith257 the recent commit seems to be an exact copy of my PR #491, including all the CI updates, as seen in your recent commit (https://github.com/zio/izumi-reflect/pull/489/commits/5f88e20b498ec0716cf419d7d343f2a9238174a0). Could you please clarify?

Cause this particular change you made was not even in the reviewer's comment (also you would say it's reference from other repo but still)

https://github.com/zio/izumi-reflect/blob/5f88e20b498ec0716cf419d7d343f2a9238174a0/.github/workflows/build.yml#L85

Ultimately, I didn't copy any of your code in the PR, but you choose to do this after asking this [question](https://github.com/zio/izumi-reflect/pull/489#issuecomment-2466476404). It’s up to the maintainer to decide how to proceed.

**Comment by varshith257** [comment]
Yeah, this is what I concerned now about what you commented ( I am not going for tick for tack , just to know you the efforts of everyone are valued) 

> Yes, I saw the comments on your PR by the maintainer and implemented them the way they need accordingly. 

I do argue the same of I have worked upon my review comments and I saw the comments on your PR by the maintainer and implemented them the way they need accordingly to close the issue

**Comment by pshirshov** [comment]
I've merged #491, I hope I didn't offend anyone... @jdegoes : I'm not sure how to handle situations like these...

**Comment by varshith257** [comment]
@pshirshov Nope! I am fine with it and respect your opinion. Happy to contribute to other issues :)

**Pull request closed without merging**
