### PR TITLE
Scala Native Scala 3

### PR DESCRIPTION
**Pull request by sideeffffect**
closes https://github.com/zio/izumi-reflect/pull/264

blocked on https://github.com/scalatest/scalatest/issues/2097
transitively blocked on https://github.com/scala/scala-xml/pull/584

### CODE REVIEW

**Comment by pshirshov** [comment]
Looks like the build needs to be fixed: 

```
[error] (izumi-reflect-thirdparty-boopickle-shadedNative / update) sbt.librarymanagement.ResolveException: Error downloading org.scala-native:nativelib_native0.4_3:0.4.2
[error]   Not found
[error]   Not found
[error]   not found: /home/runner/.ivy2/localorg.scala-native/nativelib_native0.4_3/0.4.2/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/nativelib_native0.4_3/0.4.2/nativelib_native0.4_3-0.4.2.pom
```

**Comment by sideeffffect** [comment]
Scala Native needs to be updated to 0.4.3, but that is apparently driven by sbtgen (see the PR description)

**Comment by pshirshov** [comment]
sbtgen allows you to override external dependencies directly, through `GlobalSettings`: https://github.com/7mind/sbtgen/blob/26598feb8037747a0b54b98beaae9ec2511e28f4/sbtgen/src/main/scala/izumi/sbtgen/model/GlobalSettings.scala

**Comment by neko-kai** [comment]
@sideeffffect Thank you! 🙏

**Comment by neko-kai** [comment]
@sideeffffect 
Sounds like we have to wait for scalatest to publish for 3 Native
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalatest:scalatest_native0.4_3:3.2.10
```

**Comment by sideeffffect** [comment]
Oh, I didn't know that, thanks guys.

> scalatest

I've amended the PR description. Let's hope they will publish soon :crossed_fingers:

**Review by pshirshov — APPROVED** [review]

**Comment by lolgab** [comment]
@sideeffffect scalatest 3.2.12 was released with [native0.4_3 artifacts](https://repo1.maven.org/maven2/org/scalatest/scalatest_native0.4_3/3.2.12/) :-)

**Comment by sideeffffect** [comment]
Thanks @lolgab for the notification!

Good news, @neko-kai and @pshirshov ! We should be able to merge this now :tada:

**Comment by sideeffffect** [comment]
Can we, please, have a new version of a the library published? :pray:

**Pull request merged**
