### PR TITLE
Auto-generate README File

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Review by neko-kai — APPROVED** [review]

**Comment by pshirshov** [comment]
@khajavi  Sorry, I'm gonna remove your workflow for now. It still tries to mess with readme.md in the root of the repo (see https://github.com/zio/izumi-reflect/pull/355/files) and there is this issue: https://github.com/zio/zio-sbt/issues/86

**Comment by pshirshov** [comment]
Another minor problem is that you've added `docs-plugins.sbt` instead of adding required plugins through sbtgen, so steward won't work.

**Comment by khajavi** [comment]
@pshirshov No sorry, thank you for noticing me.
> It still tries to mess with readme.md in the root of the repo (see https://github.com/zio/izumi-reflect/pull/355/files) 

Could you explain what you mean by messing? Those changes are expected from my point of view!

> and there is this issue: https://github.com/zio/zio-sbt/issues/86

Can you explain the problem, I hope I can fix that.

**Comment by pshirshov** [comment]
> expected

I won't like the idea of changing the primary readme. If you need any docs for zio website - please keep them separate from our generic readme in the root of the repo.

> explain

https://github.com/zio/zio-sbt/issues/86

 This is a problem with test reporter though I would prefer not to have two workflows until it is resolved.

**Comment by khajavi** [comment]
> I won't like the idea of changing the primary readme. 

Yes, I know, but what is the problem with that? This is the process we have taken for all projects under the zio ecosystem. 

> If you need any docs for zio website - please keep them separate from our generic readme in the root of the repo.

That PR doesn't need any docs for the zio website. It removes any handwritten readme and auto-generates that from `docs/index.md` and also some other metadata.

So instead may I ask you to review and comment on [this PR](https://github.com/zio/izumi-reflect/pull/355) and tell me unexpected changes? 

> https://github.com/zio/zio-sbt/issues/86
> This is a problem with test reporter though I would prefer not to have two workflows until it is resolved.

~~I don't know how that relates to the recent change related to the `zio-sbt-website` plugin. As I'm not familiar with that test reporter, I appreciate it if you can explain more and explain why that relates to the docs-related works.~~

**Pull request merged**
