### PR TITLE
ci: Publish docs on release

### PR DESCRIPTION
**Pull request by Dhanus3133**
/claim #458

### CODE REVIEW

**Comment by pshirshov** [comment]
Looks like we need exactly this. I'll try to review this evening, thank you!

**Review by pshirshov — CHANGES_REQUESTED** [review]
Seems like it is exactly what I wanted, but could I ask you to 

1) merge   notify-docs-release and release-docs into one task 

2) Use 7mind/github-env@main instead of setting up Scala environment manually. Just remove your checkout, setup-java and cache-action and copypaste the section from the other tasks

**Review by pshirshov — APPROVED** [review]

**Comment by pshirshov** [comment]
Actually, not there yet: https://github.com/zio/izumi-reflect/actions/runs/11767379497/job/32776047048

**Comment by pshirshov** [comment]
@Dhanus3133 we are not using zio sbt plugins and the task you relied upon comes from a zio plugin. I guess, you didn't test locally?..

**Comment by Dhanus3133** [comment]
> @Dhanus3133 we are not using zio sbt plugins and the task you relied upon comes from a zio plugin. I guess, you didn't test locally?..

Sorry about that @pshirshov, I missed verifying the plugin installation earlier. I also didn’t see your recent comment in time, and by the time I checked, it had already been resolved. Thanks for fixing it!

**Pull request merged**
