### PR TITLE
Polymorphic tag generation

### PR DESCRIPTION
**Pull request by kitlangton**
@neko-kai @pshirshov This begins to tackle https://github.com/zio/izumi-reflect/issues/103

It's certainly ugly and incomplete, but it actually works. A [test suite](https://github.com/kitlangton/zio/blob/simple-tag/core-tests/shared/src/test/scala/zio/TagCorrectnessSpec.scala) I made of outstanding Tag issues is all green with these changes. Also, the [ZStateSpec](https://github.com/zio/zio/blob/series/2.x/core-tests/shared/src/test/scala/zio/ZStateSpec.scala), which had been tagged `exceptDotty` due to the issues with [its implementation](https://github.com/zio/zio/blob/series/2.x/core/shared/src/main/scala/zio/ZIO.scala#L5328) now passes.

The only problems are, well, I made everything quite gross. I couldn't simply replace the Inspector because it's needed by the other Inspectors—and I'm not quite sure what those other Inspectors do—so I just copied it to create a version that returns an Expr (with that Expr.summon trick included). 

Also, it seems like there is a very particular and thoughtful construction of the LightTypeTag sealed trait, to deal with compatibility. I sort of just blew that up so I could test the code I wrote. (UPDATE: I mostly undid my blowing up of the LightTypeTag file—just a couple of minor changes now—though possibly still very wrong.)

I'd love to clean this up, but I thought I should push up a WIP before I went too far without feedback.

### CODE REVIEW

**Comment by kitlangton** [comment]
I was worried about the failures—but it turns out that those are the tests that were supposed to be failing in Dotty but weren't! 🥳

**Comment by pshirshov** [comment]
> I was worried about the failures—but it turns out that those are the tests that were supposed to be failing in Dotty but weren't! partying_face

We call this practice "progression tests" as an opposite to "regression".

**Comment by kitlangton** [comment]
> We call this practice "progression tests" as an opposite to "regression".

I like it! Reminds me of the monoliths in Space Odyssey:
> [the second (on the Moon) as an alarm signal designed to alert its creators that humanity had reached a sufficient technological level for space travel](https://en.wikipedia.org/wiki/Interpretations_of_2001:_A_Space_Odyssey#Clarke's_novel_as_explanation)

**Comment by pshirshov** [comment]
I think it wasn't necessary to copypaste base inspector code and introduce separate field, I think this logic can be fit into one of our "base DBs" and the inspectors just need to be extended. I guess this expr can be considered a fake parent?..

**Comment by pshirshov** [comment]
> I like it! Reminds me of the monoliths in Space Odyssey:

Well, in case of progression tests the purpose is to inform the monkey that it accidentally progressed. Most often progression tests signal about fixed problems when the engineer had no intention to fix anything, it just happens after an "irrelevant" improvement :)

**Comment by neko-kai** [comment]
> I'd love to clean this up, but I thought I should push up a WIP before I went too far without feedback.

Well, what to do next here: the inspectors deal with constructing LTT values, but for the purpose of combining tags from implicits using `Tag.appliedTag` they can be treated as opaque – you only need to call them inside your outer macro when a type or a type constructor is fully concrete.

So, the macro to implement is just the inline given in `Tag` companion object:
```scala
  inline implicit final def tagFromTagMacro[T <: AnyKind]: Tag[T] = Tag(classOf[Any], Inspect.inspect[T])
```
should become
```scala
  inline implicit final def tagFromTagMacro[T <: AnyKind]: Tag[T] = ${ TagMacro.createTagExpr[T] }
```

Where `Inspect.inspect[T]` from before is now only called for concrete types. For all types with type parameters Expr.summon will be used recursively to summon `Tag`'s for type parameters, `HKTag`'s for constructors that are themselves type parameters and the result should be an Expr that contains a call to `Tag.appliedTag` or `Tag.refinedTag` with all of the summoned parts of a type.

The LightTypeTag itself doesn't need to be modified because the functions to combine tags from implicits are already there in `Tag` companion object – well, one thing you may have to touch is when you get to Unions, there's only a combination function for intersections and refinements `Tag.refinedTag` - a new function for unions will have to be added there.

**Comment by kitlangton** [comment]
@neko-kai Aha! I get it! I think I get it, at least!
Okay. Basically, I need implement the TagMacro from Scala 2 (which I believe @pshirshov mentioned somewhere previously, but I just didn't understand what that meant at the time). I will give this a shot.

**Comment by kitlangton** [comment]
Closing in favor of #239

**Pull request closed without merging**
